Areas/City/Controllers/LOC_CityController.cs
using AdminPanel_New.DAL.LOC_CityDAL;
using AdminPanel_New.DAL.LOC_StateDAL;
using AdminPanel_Theme.Areas.City.Models;
using AdminPanel_Theme.BAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_Theme.Areas.City.Controllers
{
    [CheckAccess]
    [Area("City")]
    [Route("City/[controller]/[action]")]
    public class LOC_CityController : Controller
    {
        LOC_CityDAL dalLOC_CityDAL = new LOC_CityDAL();
        LOC_StateDAL dalLOC_StateDAL = new LOC_StateDAL();

        #region LOC_CityList Controller
        public IActionResult LOC_CityList()
        {
            DataTable dt = dalLOC_CityDAL.dbo_PR_LOC_City_SelectAll();
            ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
            ViewBag.StateList = dalLOC_CityDAL.DropDownState();
            return View(dt);
        }
        #endregion

        #region ADD Method 
        public IActionResult Add(int? CityID)
        {
            if (CityID == null)
            {
                ViewBag.StateList = dalLOC_CityDAL.DropDownState();
                return View("AddEditCity");
            }
            else
            {
                LOC_CityModel model = dalLOC_CityDAL.PR_LOC_City_SelectByPK(CityID);
                ViewBag.StateList = dalLOC_CityDAL.DropDownState();
                return View("AddEditCity", model);
            }
        }
        #endregion

        #region AddEditCity
        public IActionResult AddEditCity(LOC_CityModel model)
        {
            if (dalLOC_CityDAL.SaveCity(model))
            {
                return RedirectToAction("LOC_CityList");
            }
            return View("AddEditCity");

        }
        #endregion

        #region Delete
        public IActionResult Delete(int? CityID)
        {
            dalLOC_CityDAL.PR_LOC_City_Delete(CityID);
            return RedirectToAction("LOC_CityList");
        }
        #endregion

        public IActionResult DropDownByCountryForState(int CountryID)
        {
            var model = dalLOC_CityDAL.PR_LOC_State_SelectComboBoxByCountryID(CountryID);
            return Json(model);
        }

        #region SearchCity
        public IActionResult SearchCity(string CityName)
        {
            DataTable dt = dalLOC_CityDAL.PR_City_SelectByCityName(CityName);
            return View("LOC_CityList", dt);
        }
        #endregion

        #region LOC_CityFilter
        public IActionResult LOC_CityFilter(LOC_CityFilterModel FilterModel) {
            DataTable dt= dalLOC_CityDAL.PR_City_Filter(FilterModel);
            ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
            ViewBag.StateList = dalLOC_CityDAL.DropDownState();
            ModelState.Clear();
            return View("LOC_CityList", dt);

        }
        #endregion
    }
}
    

Areas/Country/Controllers/LOC_CountryController.cs
using AdminPanel_New.DAL.LOC_CountryDAL;
using AdminPanel_Theme.Areas.Country.Models;
using AdminPanel_Theme.BAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_Theme.Areas.Country.Controllers
{
    [CheckAccess]
    [Area("Country")]
    [Route("Country/[controller]/[action]")]
    public class LOC_CountryController : Controller
    {
        LOC_CountryModel modelLOC_Country = new LOC_CountryModel();
        LOC_CountryDAL dalLOC_CountryDAL = new LOC_CountryDAL();

        #region LOC_CountryList Controller
        public IActionResult LOC_CountryList()
        {
            DataTable dt = dalLOC_CountryDAL.dbo_PR_LOC_Country_SelectAll();
            return View(dt);
        }
        #endregion

        #region Add NAvigator For Render PAge
        public IActionResult Add(int? CountryID)
        {


            LOC_CountryModel model = dalLOC_CountryDAL.PR_LOC_Country_SelectByPK(CountryID);
            if (model != null)
            {
                return View("AddEditCountry", model);
            }
            else
            {
                return View("AddEditCountry");
            }
        }
        #endregion

        #region Add /Edit Page Controller
        public IActionResult AddEditCountry(LOC_CountryModel modelLOC_CountryModel)
        {
            if (ModelState.IsValid)
            {
                if (dalLOC_CountryDAL.SaveCountry(modelLOC_CountryModel))
                {
                    if (modelLOC_CountryModel.CountryID == null)
                    {
                        TempData["CountryInsertMsg"] = "Record Inserted Successfully";
                        return RedirectToAction("LOC_CountryList");
                    }
                    else
                        return RedirectToAction("LOC_CountryList");
                }
            }
            return View("AddEditCountry");
        }
        #endregion

        #region Delete 
        public IActionResult Delete(int? CountryID)
        {
            dalLOC_CountryDAL.PR_LOC_deleteCity_FollowedBy_Country(CountryID);
            dalLOC_CountryDAL.PR_LOC_deleteState_FollowedBy_Country(CountryID);
            dalLOC_CountryDAL.PR_LOC_Country_Delete(CountryID);
            return RedirectToAction("LOC_CountryList");
        }
        #endregion

        #region SearchContry
        public IActionResult SearchContry(string CountryName)
        {
            DataTable dt = dalLOC_CountryDAL.PR_Country_SelectByCountryName(CountryName);
            return View("LOC_CountryList", dt);
        }
        #endregion

        #region LOC_CountryFilter
        public IActionResult LOC_CountryFilter(LOC_CountryFilterModel filterModel)
        {
            DataTable dt= dalLOC_CountryDAL.PR_Country_Filter(filterModel);
            ModelState.Clear();
            return View("LOC_CountryList", dt);
        }
        #endregion
    }
}

Areas/States/Controllers/LOC_StateController.cs
using AdminPanel_New.DAL.LOC_StateDAL;
using AdminPanel_Theme.Areas.States.Models;
using AdminPanel_Theme.BAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using System.Data;

namespace AdminPanel_Theme.Areas.States.Controllers
{
    [CheckAccess]
    [Area("States")]
    [Route("States/[controller]/[action]")]
    public class LOC_StateController : Controller
    {
        LOC_StateDAL dalLOC_StateDAL = new LOC_StateDAL();
        #region LOC_StateList
        public IActionResult LOC_StateList()
        {
            List<LOC_StateModel> models = new List<LOC_StateModel>();
            DataTable dt = dalLOC_StateDAL.dbo_PR_LOC_State_SelectAll();
            return View(dt);
        }
        #endregion

        #region ADD
        public IActionResult Add(int? StateID)
        {
            if (StateID == null)
            {
                //ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
                return View("AddEditState");
            }
            else
            {
                LOC_StateModel model = dalLOC_StateDAL.PR_LOC_State_SelectByPK(StateID);
                //ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
                return View("AddEditState", model);
            }

        }
        #endregion

        #region ADD & Edit State
        public IActionResult AddEditState(LOC_StateModel model)
        {
            LOC_StateDAL dalLOC_StateDAL = new LOC_StateDAL();

            if (dalLOC_StateDAL.SaveState(model))
            {
                return RedirectToAction("LOC_StateList");
            }

            return View();
        }
        #endregion

        #region Delete
        public IActionResult Delete(int? StateID)
        {
            dalLOC_StateDAL.PR_LOC_deleteCity_FollowedBy_States(StateID);
            dalLOC_StateDAL.PR_LOC_State_Delete(StateID);
            return RedirectToAction("LOC_StateList");
        }
        #endregion

        #region SearchState
        public IActionResult SearchState(string StateName)
        {
            DataTable dt = dalLOC_StateDAL.PR_State_SelectByStateName(StateName);
            return View("LOC_StateList", dt);
        }
        #endregion

        #region LOC_StateFilter
        public IActionResult LOC_StateFilter(LOC_StateFilterModel filterModel)
        {
            DataTable dt=dalLOC_StateDAL.PR_State_Filter(filterModel);
            ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
            ModelState.Clear();
            return View("LOC_StateList", dt);

        }
        #endregion
    }
}

Views/Shared/_Layout.cshtml
@using AdminPanel_Theme.BAL;
@{
    string name = CV.UserName();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPanel_Theme</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminPanel_Theme.styles.css" asp-append-version="true" />

    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Bootstrap Components &rsaquo; Buttons &mdash; Stisla</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="~/assets/modules/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/modules/fontawesome/css/all.min.css">

    <!-- CSS Libraries -->
    <!-- Template CSS -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/components.css">
    <!-- Start GA -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-94034622-3');
    </script>
</head>
<body>

    <header>
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            <div class="navbar-bg"></div>
            <nav class="navbar navbar-expand-lg main-navbar">
                
                <form class="form-inline mr-auto">
                    <ul class="navbar-nav mr-3">
                        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
                        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
                    </ul>
                </form>
                    <ul class="navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                                <img alt="image" src="~/assets/img/avatar/avatar-1.png" class="rounded-circle mr-1">
                                
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <div class="dropdown-divider"></div>
                                <form  asp-area="SEC_User" asp-controller="SEC_User" asp-action="Logout"  class="dropdown-item has-icon text-danger">
                                    <input type="submit" class="fas fa-sign-out-alt" value="Logout"/>
                                </form>
                            </div>
                        </li>
                    </ul>
            </nav>
            <div class="main-sidebar sidebar-style-2">
                <aside id="sidebar-wrapper">
                    <div class="sidebar-brand">
                        <a href="index.html">Admin</a>
                    </div>
                    <div class="sidebar-brand sidebar-brand-sm">
                        <a href="index.html">Ad</a>
                    </div>
                    <ul class="sidebar-menu">
                        <li class="menu-header">Admin</li>
                        <li class="dropdown active">
                            <a href="#" class="nav-link has-dropdown"><i class="fas fa-map-marker-alt"></i><span>Location</span></a>
                            <ul class="dropdown-menu">
                                @* <li class=""><a class="nav-link" asp-area="Country" asp-controller="LOC_Country" asp-action="LOC_CountryList">Country</a></li> *@
                                <li class=""><a class="nav-link" asp-area="States" asp-controller="LOC_State" asp-action="LOC_StateList">State</a></li>
                                <li class=""><a class="nav-link" asp-area="City" asp-controller="LOC_City" asp-action="LOC_CityList">City</a></li>

                            </ul>
                        </li>
                            <li class="dropdown active">
                                <a href="#" class="nav-link has-dropdown"><i class="far fa-file-alt"></i><span>Universities</span></a>
                                <ul class="dropdown-menu">
                                    @* <li class=""><a class="nav-link" asp-area="Country" asp-controller="LOC_Country" asp-action="LOC_CountryList">Country</a></li> *@
                                    <li class=""><a class="nav-link" asp-area="FC_Program" asp-controller="FC_Program" asp-action="FC_ProgramList">Program</a></li>
                                    @* <li class=""><a class="nav-link" asp-area="City" asp-controller="LOC_City" asp-action="LOC_CityList">City</a></li> *@

                                </ul>
                            </li>
                        @* <li class="dropdown ">
                            <a href="#" class="nav-link has-dropdown"><i class="far fa-user"></i><span>Users</span></a>
                            <ul class="dropdown-menu">
                                <li class=""><a class="nav-link" asp-area="Branch" asp-controller="MST_Branch" asp-action="MST_BranchList">Branch</a></li> 
                                <li class=""><a class="nav-link" asp-area="Student" asp-controller="MST_Student" asp-action="MST_StudentList">Student</a></li>
                            </ul>
                        </li> *@
                    </ul>
                </aside>
            </div>
        </div>
    </div>
    </header>

    <main id="main" class="main">
        @RenderBody()
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- General JS Scripts -->
    <script src="~/assets/modules/jquery.min.js"></script>
    <script src="~/assets/modules/popper.js"></script>
    <script src="~/assets/modules/tooltip.js"></script>
    <script src="~/assets/modules/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/modules/nicescroll/jquery.nicescroll.min.js"></script>
    <script src="~/assets/modules/moment.min.js"></script>
    <script src="~/assets/js/stisla.js"></script>

    <!-- JS Libraies -->
    <script src="~/assets/modules/prism/prism.js"></script>
    <!-- Page Specific JS File -->
    <script src="~/assets/js/page/bootstrap-modal.js"></script>

    <!-- Template JS File -->
    <script src="~/assets/js/scripts.js"></script>
    <script src="~/assets/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Error.cshtml
@RenderBody()

Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Login &mdash; Stisla</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="~/assets/modules/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/modules/fontawesome/css/all.min.css">

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="~/assets/modules/bootstrap-social/bootstrap-social.css">

    <!-- Template CSS -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/components.css">
    <!-- Start GA -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-94034622-3');
    </script>
    <!-- /END GA -->
</head>

<body>
    <div id="app">
        <section class="section">
            <div class="container mt-5">
                @RenderBody()
            </div>
        </section>
    </div>

    <!-- General JS Scripts -->
    <script src="~/assets/modules/jquery.min.js"></script>
    <script src="~/assets/modules/popper.js"></script>
    <script src="~/assets/modules/tooltip.js"></script>
    <script src="~/assets/modules/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/modules/nicescroll/jquery.nicescroll.min.js"></script>
    <script src="~/assets/modules/moment.min.js"></script>
    <script src="~/assets/js/stisla.js"></script>

    <!-- JS Libraies -->
    <!-- Page Specific JS File -->
    <!-- Template JS File -->
    <script src="~/assets/js/scripts.js"></script>
    <script src="~/assets/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_Layout_User.cshtml
@using AdminPanel_Theme.BAL
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Layout &rsaquo; Top Navigation &mdash; Stisla</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="~/assets/modules/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/modules/fontawesome/css/all.min.css">

    <!-- CSS Libraries -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
    <!-- Template CSS -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/components.css">
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-94034622-3');
    </script>
    <!-- /END GA -->
</head>

<body class="layout-3">
    <div id="app">
        <div class="main-wrapper container">
            <div class="navbar-bg"></div>
            <nav class="navbar navbar-expand-lg main-navbar">
                <a href="index.html" class="navbar-brand sidebar-gone-hide">Stisla</a>
                <a href="#" class="nav-link sidebar-gone-show" data-toggle="sidebar"><i class="fas fa-bars"></i></a>
                <div class="nav-collapse">
                    <a class="sidebar-gone-show nav-collapse-toggle nav-link" href="#">
                        <i class="fas fa-ellipsis-v"></i>
                    </a>
                    <ul class="navbar-nav">
                        <li class="nav-item active"><a href="#" class="nav-link">Application</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Report Something</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Server Status</a></li>
                    </ul>
                </div>
                <form class="form-inline ml-auto">
                    <ul class="navbar-nav">
                        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
                    </ul>
                    <div class="search-element">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
                        <button class="btn" type="submit"><i class="fas fa-search"></i></button>
                        <div class="search-backdrop"></div>
                        <div class="search-result">
                            <div class="search-header">
                                Histories
                            </div>
                            <div class="search-item">
                                <a href="#">How to hack NASA using CSS</a>
                                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
                            </div>
                            <div class="search-item">
                                <a href="#">Kodinger.com</a>
                                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
                            </div>
                            <div class="search-item">
                                <a href="#">#Stisla</a>
                                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
                            </div>
                            <div class="search-header">
                                Result
                            </div>
                            <div class="search-item">
                                <a href="#">
                                    <img class="mr-3 rounded" width="30" src="~/assets/img/products/product-3-50.png" alt="product">
                                    oPhone S9 Limited Edition
                                </a>
                            </div>
                            <div class="search-item">
                                <a href="#">
                                    <img class="mr-3 rounded" width="30" src="~/assets/img/products/product-2-50.png" alt="product">
                                    Drone X2 New Gen-7
                                </a>
                            </div>
                            <div class="search-item">
                                <a href="#">
                                    <img class="mr-3 rounded" width="30" src="~/assets/img/products/product-1-50.png" alt="product">
                                    Headphone Blitz
                                </a>
                            </div>
                            <div class="search-header">
                                Projects
                            </div>
                            <div class="search-item">
                                <a href="#">
                                    <div class="search-icon bg-danger text-white mr-3">
                                        <i class="fas fa-code"></i>
                                    </div>
                                    Stisla Admin Template
                                </a>
                            </div>
                            <div class="search-item">
                                <a href="#">
                                    <div class="search-icon bg-primary text-white mr-3">
                                        <i class="fas fa-laptop"></i>
                                    </div>
                                    Create a new Homepage Design
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
                <ul class="navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                            <img alt="image" src="~/assets/img/avatar/avatar-1.png" class="rounded-circle mr-1">
                            @if (CV.UserName() != null)
                            {
                                <div class="d-sm-none d-lg-inline-block">Hiii, @CV.UserName()</div>
                            }
                            @* <div class="d-sm-none d-lg-inline-block">Hiii,@CV.UserName()</div> *@
                            <div class="dropdown-menu dropdown-menu-right">

                                @if (CV.UserName() == null)
                                {
                                    <form>
                                    <a asp-area="SEC_User" asp-controller="SEC_User" asp-action="SEC_UserLogin" class="dropdown-item has-icon">
                                        <i class="fas fa-bolt"></i> Login
                                    </a>
                                    </form> 

                                }
                                <div class="dropdown-divider"></div>
                                @if (CV.UserName() != null)
                                {
                                    <form>
                                    <a asp-area="SEC_User" asp-controller="SEC_User" asp-action="Logout" class="dropdown-item has-icon text-danger">
                                        <i class="fas fa-sign-out-alt"></i> Logout
                                    </a>
                                    </form>
                                }
                            </div>
                        </a>
                    </li>
                </ul>
            </nav>

            <nav class="navbar navbar-secondary navbar-expand-lg">
                <div class="container">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Dashboard</span></a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a href="index-0.html" class="nav-link">General Dashboard</a></li>
                                <li class="nav-item"><a href="index.html" class="nav-link">Ecommerce Dashboard</a></li>
                            </ul>       
                        </li>
                        <li class="nav-item active">
                            <a href="#" class="nav-link"><i class="far fa-heart"></i><span>Top Navigation</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" data-toggle="dropdown" class="nav-link has-dropdown"><i class="far fa-clone"></i><span>Multiple Dropdown</span></a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a href="#" class="nav-link">Not Dropdown Link</a></li>
                                <li class="nav-item dropdown">
                                    <a href="#" class="nav-link has-dropdown">Hover Me</a>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                                        <li class="nav-item dropdown">
                                            <a href="#" class="nav-link has-dropdown">Link 2</a>
                                            <ul class="dropdown-menu">
                                                <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                                                <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                                                <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                                            </ul>
                                        </li>
                                        <li class="nav-item"><a href="#" class="nav-link">Link 3</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Main Content -->
            <div class="main-content">
                <section class="section">
                    <div class="section-header">
                        <h1>Top Navigation</h1>
                        <div class="section-header-breadcrumb">
                            <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                            <div class="breadcrumb-item"><a href="#">Layout</a></div>
                            <div class="breadcrumb-item">Top Navigation</div>
                        </div>
                    </div>


                    @* <div class="section-body">
                    <h2 class="section-title">This is Example Page</h2>
                    <p class="section-lead">This page is just an example for you to create your own page.</p>
                    <div class="card">
                    <div class="card-header">
                    <h4>Example Card</h4>
                    </div>
                    <div class="card-body">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                    <div class="card-footer bg-whitesmoke">
                    This is card footer
                    </div>
                    </div>
                    </div> *@
                </section>
            </div>
            <footer class="main-footer">
                <div class="footer-left">
                    Copyright &copy; Jadoo 000000
                </div>
                <div class="footer-right">
                </div>
            </footer>
        </div>
    </div>

    @RenderBody()

    <!-- General JS Scripts -->
    <script src="~/assets/modules/jquery.min.js"></script>
    <script src="~/assets/modules/popper.js"></script>
    <script src="~/assets/modules/tooltip.js"></script>
    <script src="~/assets/modules/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/modules/nicescroll/jquery.nicescroll.min.js"></script>
    <script src="~/assets/modules/moment.min.js"></script>
    <script src="~/assets/js/stisla.js"></script>

    <!-- JS Libraies -->
    <script src="~/assets/modules/prism/prism.js"></script>
    <!-- Page Specific JS File -->
    <script src="~/assets/js/page/bootstrap-modal.js"></script>

    <!-- Template JS File -->
    <script src="~/assets/js/scripts.js"></script>
    <script src="~/assets/js/custom.js"></script>
    <!-- Template JS File -->
    <script src="~/assets/js/scripts.js"></script>
    <script src="~/assets/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>